// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path"
import { defineConfig } from "prisma/config";

dotenv.config({
  path:path.resolve(import.meta.dirname,"../../.env")
})
console.log("djshsjvf  ",process.env.DATABASE_URL)

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
